### ISSUE TITLE
Vintages and discontinued series

### ISSUE THREAD

**Issue by omuelle** [mbannert/timeseriesdb#102]
It's currently not possible to provide an end date for each vintage. This is kind of annoying when dealing with discontinued series. Say I want to load all currently valid series. The discontinued series will be part of it, since they're basically valid for all eternity. It would make more sense if their last values are only valid for a month or a quarter or a year, depending on the frequency. In fact for fixed frequency series the values should always be valid only for the given period.

Thoughts?

**Comment by mbannert** [comment]
I guess we're still learning all the different aspects of actually working with vintage data. So far we have mostly archived them. However, I saw how vintages were actually read and processed in a very recent project on data revisions.

Though I do see what's annoying to you about the current concept, I still think it's inevitable to leave an open end to the most recent vintage: assume a vintage is not updated for a while because the publication is 1-2 months late. So at that point in time whatever you got is the best you can get until the new data comes out. So maybe a vintage is just active a little longer until the data come out. In other words: you cannot assume you know the end date. And by definition a vintage comes to an end the moment the new data are out. 

However I guess I got a cure for your problem:
As I raised in another issue we should have a function which reads all vintages of a particular key. If this function had an option to recognize discontinued series and ignore them we should all be happy. We could use frequency as you suggested to figure out whether there should have been a release and thus the series could be considered abandoned.

**Comment by HomoCodens** [comment]
I'm with Matt here.
Vintages as we understood them up to this point were always valid until new data come out.

I guess what you mean is not so much "currently valid" series as "currently relevant"?

A census of a town that disappeared in '93 would still be **valid** today but wouldn't really matter anymore.

I suppose some query to exclude all series where the last valid_from date (i.e. update) is more than one frequency tick in the past could be constructed.

**Comment by omuelle** [comment]
Yeah I guess you're right. The frequency of updates isn't necessarily the same as the frequency of the series. I thought it would be nice to know whether a vintage is "missing", but that's kind of impossible to determine.
