### ISSUE TITLE
Rights Management PoC

### ISSUE THREAD

**Issue by mbannert** [mbannert/timeseriesdb#112]
access levels: 
- public (everybody)
- main (everybody within / organization)
- restricted (only some within the organization) 

role: 
- reader
- updater
- admin

**Comment by HomoCodens** [comment]
Since we want to only let non-admins access the schema through functions the section `Writing SECURITY DEFINER Functions Safely` from https://www.postgresql.org/docs/11/sql-createfunction.html is probably relevant.

Also we need to figure out which user to define the functions as. All out root might be a bit much.
