### ISSUE TITLE
add release date option

### ISSUE THREAD

**Issue by mbannert** [mbannert/timeseriesdb#28]
- readTimeSeries
- storeTimeSeries

**Comment by HomoCodens** [comment]
Also
* createTables.R

**Comment by HomoCodens** [comment]
**readTimeSeries**
We need to decide whether to include a data point or not on the DB.
1) To prevent time zone problems
2) To prevent users from getting at data by fiddling with their system clocks

```
        sprintf("
                BEGIN;
                CREATE TEMPORARY TABLE ts_read (ts_key text PRIMARY KEY) ON COMMIT DROP;
                INSERT INTO ts_read(ts_key) VALUES %s;
                
                SELECT ts_key, row_to_json(t)::text AS ts_json_records
                FROM (
                SELECT tm.ts_key, ts_data, ts_frequency
                FROM %s.%s tm
                JOIN ts_read tr
                ON (tm.ts_key = tr.ts_key)
                ) t;",
              series, schema, tbl) 
```
We also don't want the check in the query defined above since that could also be hacked locally.
We therefore either need a db function that performs the same read as the query above or possibly the release date could be checked in the existing `row_to_json`.

**Comment by HomoCodens** [comment]
Also, are there edge cases where more than one data point is not released yet?

**Comment by HomoCodens** [comment]
I think the only table that needs the additional column is _timeseries_main_, right?

How about an upgrade function to make the necessary table alteration(s) in an existing timeseriesdb?
