### ISSUE TITLE
when storing same vintages key with empty vintage is added

### ISSUE THREAD

**Issue by mbannert** [mbannert/timeseriesdb#41]
storing same vintage twice leads to storing series with an empty ts_validity, only after that you get a PK constraint violation.

**Comment by HomoCodens** [comment]
```
UPDATE %s.%s
                        SET ts_validity = ('['|| 
                        COALESCE(lower(%s.ts_validity):: TEXT,'') ||
                        ','|| 
                        COALESCE(lower(ts_updates.ts_validity) :: TEXT,'') ||
                        ')'):: DATERANGE
                       FROM ts_updates
                       WHERE ts_updates.ts_key = %s.ts_key
                       AND %s.ts_validity @> %s;
```

This produces an empty date range if the same date_from is provided twice since the upper bound is set to the lower bound of the range from `ts_updates` (line 5 in the posted code).

In other words: The table should only be updated if the new lower bound is greater than the current one.

**Comment by mbannert** [comment]
I don't think a vintage should be updated at all. There should be no way for the ordinary user to overwrite any vintage information. If a particular time frame is (partly) covered for a particular key, there's no way to overwrite it. Otherwise we risk loosing information we can't reproduce.

**Comment by HomoCodens** [comment]
The vintage data themselves are not overwritten, just the validity range.
If I understand it correctly, an insert into the vintages table works as follows:
1) Set the upper bound of the most recent vintage to the lower bound of the one being inserted (i.e. "close" that window)
2) Insert the new vintage with a range `[new_date, )` of no upper bound is provided, `[new_lower, new_upper)` otherwise.

The "problem" is that this relies on the user supplying steadily increasing (or otherwise valid) dates.

**Comment by mbannert** [comment]
Well said, this is exactly how it works. Yet, that's the nature of vintages. If the user doesn't supply the correct date, she should be blocked + plus a smart error message that tells her about the bad date. All I don't want is, this to cause these fishy empty validity records. 

Also, I feel even validity should not be updated. Am I missing something here?
