### ISSUE TITLE
Fail to save meta info for ts that appear only in timeseries_vintages

### ISSUE THREAD

**Issue by sboriss** [mbannert/timeseriesdb#65]
When I try to insert meta information for time series that are only saved in vintages, i.e. only in timeseries_vintages, (hence does not appear in timeseries_main) the following error occurs: 

Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  insert or update on table "meta_data_localized" violates foreign key constraint "meta_data_localized_ts_key_fkey"
DETAIL:  Key (ts_key)=(ts1) is not present in table "timeseries_main".
)
Warning in postgresqlQuickSQL(conn, statement, ...) :
  Could not create execute: LOCK TABLE tsdb.meta_data_localized IN EXCLUSIVE MODE;
                                      UPDATE tsdb.meta_data_localized
                                      SET meta_data = md_updates.meta_data,
                                      locale_info = md_updates.locale
                                      FROM md_updates
                                      WHERE md_updates.ts_key = tsdb.meta_data_localized.ts_key
                                      AND md_updates.locale = tsdb.meta_data_localized.locale_info;
                                      
                                      ---
                                      INSERT INTO tsdb.meta_data_localized
                                      SELECT md_updates.ts_key,
                                      md_updates.locale,
                                      md_updates.meta_data
                                      FROM md_updates
                                      LEFT OUTER JOIN tsdb.meta [... truncated]
Meta information updated.

I am not sure whether this has been done on purpose or not. A way around it would be to create an artificial time series with the same name in "timeseries_main", but again not sure whether it is a proper solution.

**Comment by mbannert** [comment]
Yes, this was done on purpose with the idea in mind that vintages are a version / revision of a current time series. Due to the foreign key constraint it is not possible to have meta information without a main series. One could argue that all series should be stored in the vintage table, but this might lead to a substantial increase in time needed for `SELECT` statements. 

Afaik it is not possible to have a foreign key that uses either table A OR table B. Hence using timeseries_main and timeseries_vintages at once won't work. 

Yet, I do understand your need and I think we should consider this. Might be a bit of a conceptual overhaul to do as we intend to offer more vintages related feature. But it's certainly in our best interest to avoid artificial series.
