### ISSUE TITLE
storeTimeSeries introduces unnecessary digits... 

### ISSUE THREAD

**Issue by mbannert** [mbannert/timeseriesdb#70]
```
readTimeSeries("ch.seco.gdp_exp.real_y_b1b_pct",con,schema = "pblc_timeseries")
```

returns 1.x digits and seems to run an `as.numeric` before returning the values. 
However, the db stores all info as character, which is fine, but we should make sure we have numeric values before turning them to chars for storing

**Comment by HomoCodens** [comment]
I think R is just not telling you the whole story when you look at the numbers in manually:

```R
library(timeseriesdb)
con <- kofbts::kofDbConnect()
timeseries <- readTimeSeries("ch.seco.gdp_exp.real_y_b1b_pct",con,schema = "pblc_timeseries")
c(timeseries$ch.seco.gdp_exp.real_y_b1b_pct)
options(digits = 20)
c(timeseries$ch.seco.gdp_exp.real_y_b1b_pct)
options(digits = 7)
dbDisconnect(con)
```

There is some sneaky noise hiding after around the 16th digit which I assume comes from floating point imprecisions when calculating the time series in the first place.

Since restricting the precision in timeseriesdb may be questionable, we should truncate the time series numbers before storing them to the DB in our internal aggregation processes.

**Comment by HomoCodens** [comment]
After the switch to JSON this won't be an issue anymore.
We'll let jsonlite decide with `digits = NA`.
